general:
  verbose: true
steps:
  mtaBuild:
    buildTarget: 'CF'
    applicationName: 'Kakashi'
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'CF'
      apiEndpoint: '<CF Endpoint>'
      org: '<CF Organization>'
      space: '<CF Space>'
